### ISSUE TITLE
What is 'Dymaxion4Lyfe'?

### ISSUE THREAD

**Issue by samwilson** [geogeeks-au/geogeeks-au.github.io#2]
It's in your title:
https://github.com/geogeeks-au/geogeeks-au.github.io/blob/master/index.html#L9

Are you trying to wheel us in with with talk of funky groovy geo nerdery, only to peddle weight-loss pills at us?!

;)

**Comment by johnwbryant** [comment]
It's the compulsory tattoo new initiates must get on their forearm ;)

**Comment by samwilson** [comment]
I knew it!

My mum always told me that postgres was just a gateway to harder things...
