### ISSUE TITLE
Generated files in _site/workshops

### ISSUE THREAD

**Issue by VeckoTheGecko** [geogeeks-au/geogeeks-au.github.io#30]
Been working with the dev environment for the website, and running `bundle exec jekyll serve` populates a bunch of files in the `_site/workshops` folder.

I assume these files aren't meant to be git-tracked, so should this line be removed?:
https://github.com/geogeeks-au/geogeeks-au.github.io/blob/43f91b2095ad2f95507fb2cdaf16933a1ad6d6ed/.gitignore#L3

**Comment by samwilson** [comment]
No I think the idea is that Jekyll allows static HTML files in that directory, and we wanted to keep historical stuff around. It could probably also be moved to a different location.

**Comment by samwilson** [comment]
Oh, the *were* moved to a different location! `/workshops/2017-leaflet`

So yeah, you're probably right, the gitignore is out of date.

I think the main idea is that https://geogeeks.org/workshops/2017-leaflet/ keeps on working.
