### ISSUE TITLE
Calendar integrations

### ISSUE THREAD

**Issue by VeckoTheGecko** [geogeeks-au/geogeeks-au.github.io#33]
Looking at the site setup, there seems to be duplication between `_data/events.yml` and the hosting platform for the event, forcing maintainers to update information on two separate platforms (GitHub + the hosting site).

Looking at the hosting platforms, we mainly use www.osmcal.org (OSM meetups), and Humanitix (GeoGeeks events).

There is tooling/widgets for embedding lists of osmcal and Humanitix events directly in websites:
- Humanitix: Event listing widget
  - [Docs](https://humanitix.atlassian.net/wiki/spaces/CS/pages/1228538204/Sell+tickets+and+showcase+events+on+your+website+with+widgets?parentProduct=JSM-Portal&initialAllowedFeatures=&locale=en-US#%5BhardBreak%5D%5BhardBreak%5D%F0%9F%97%83%EF%B8%8F-Event-listing-widget%5BhardBreak%5D)
  - [Demo from event dashboard](https://user-images.githubusercontent.com/36369090/219846638-dbafda13-d23a-43c7-8535-e57e8efceed9.png)
- osmcal
  - [jbelien/openstreetmap-calendar-widget](https://github.com/jbelien/openstreetmap-calendar-widget) for the OSM events (as suggested in the [osmcal docs](https://osmcal.org/documentation/)).
  
## Pros
- Zero site maintainence (events auto-populated/updated as they're changed)
- [Humanitix] Tighter branding integration with Humanitix website (potentially prompting people to follow GeoGeeks on Humanitix)

## Cons
- Less flexibility on event metadata
- [Humanitix] Less flexibility on event listing UI
- Requires lock-in to Humanitix and osmcal as event providers
- Event creators need access to OSM/Humanitix accounts

## Other note
- Requires splitting GeoGeeks and OSM events into 2 sections

**Comment by samwilson** [comment]
Do each of these have APIs that we could use? Perhaps we could have the best of both worlds, and have single-entry but still list the events intermingled chronologically?

Does Humanitix keep event pages around for long after an event? If not, I'd worry about losing the history of when we did what.

**Comment by VeckoTheGecko** [comment]
> Do each of these have APIs that we could use?
They both have public APIs ([OSMcal API](https://osmcal.org/static/api.html) and [Humanitix API](https://api.humanitix.com/v1/documentation/static/index.html)), though neither look extensive when it comes to query parameters and querying by organiser. Could paginate through all the upcoming events in Australia and then filter down by organiser ID (for Humanitix), or more precise location (for OSMcal, since organiser isn't returned by the API)

> Does Humanitix keep event pages around for long after an event?
Really not sure on this point, couldn't find anything in their policies. I doubt they would delete past events as I've never heard that sort of purging data to be a thing (though my ignorance is not great reasoning). *Do other hosting platforms delete past events?*

---
Inherently relying on OSMcal and Humanitix as the source of truth for the events is trusting them to manage the data, and means that the data wouldn't be conveniently stored in a text document (though, assuming they don't delete data, can be retrived just by spending 10 mins copying and pasting from the web UI). Whether that compromise is worth it is not really up to me (since I'm not updating the yaml at the moment anyway 😁).

**Comment by BudgieInWA** [comment]
Now that we have a good system for representing events on this site and adding lots of juicy details, I think we have decided that our version of the events is the source of truth, and external listings are secondary.

Automating the process of pushing an event to one of the external listing does sound tempting, but I don't think the effort of writing and maintaining such automation would be worth it.

So I'm gonna close this, and point y'all towards #53 instead :)
